// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyFitQuest.API.Models;

public partial class Audit_Log
{
    public int audit_id { get; set; }

    public int? user_id { get; set; }

    public string action { get; set; }

    public string target { get; set; }

    public DateTime? timestamp { get; set; }

    public string ip_address { get; set; }

    public virtual User user { get; set; }
}