// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyFitQuest.API.Models;

public partial class Daily_Quest
{
    public int quest_id { get; set; }

    public string title { get; set; }

    public string description { get; set; }

    public int points { get; set; }

    public DateTime? created_at { get; set; }

    public virtual ICollection<User_Quest> User_Quests { get; set; } = new List<User_Quest>();
}