// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyFitQuest.API.Models;

public partial class Meal
{
    public int meal_id { get; set; }

    public string meal_name { get; set; }

    public int calories { get; set; }

    public double protein { get; set; }

    public double carbs { get; set; }

    public double fat { get; set; }

    public DateTime? created_at { get; set; }

    public virtual ICollection<User_Meal_Plan> User_Meal_Plans { get; set; } = new List<User_Meal_Plan>();
}