// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyFitQuest.API.Models;

public partial class Permission
{
    public int permission_id { get; set; }

    public string permission_name { get; set; }

    public string description { get; set; }

    public virtual ICollection<Role_Permission> Role_Permissions { get; set; } = new List<Role_Permission>();
}