// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyFitQuest.API.Models;

public partial class Role
{
    public int role_id { get; set; }

    public string role_name { get; set; }

    public string description { get; set; }

    public DateTime? created_at { get; set; }

    public virtual ICollection<Role_Permission> Role_Permissions { get; set; } = new List<Role_Permission>();

    public virtual ICollection<User_Role> User_Roles { get; set; } = new List<User_Role>();
}