// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyFitQuest.API.Models;

public partial class Role_Permission
{
    public int role_permission_id { get; set; }

    public int role_id { get; set; }

    public int permission_id { get; set; }

    public virtual Permission permission { get; set; }

    public virtual Role role { get; set; }
}