// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyFitQuest.API.Models;

public partial class User_Quest
{
    public int user_quest_id { get; set; }

    public int user_id { get; set; }

    public int quest_id { get; set; }

    public DateTime? completed_at { get; set; }

    public virtual Daily_Quest quest { get; set; }

    public virtual User user { get; set; }
}