// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyFitQuest.API.Models;

public partial class User_Meal_Plan
{
    public int user_meal_id { get; set; }

    public int user_id { get; set; }

    public int meal_id { get; set; }

    public DateOnly date_assigned { get; set; }

    public string status { get; set; }

    public virtual Meal meal { get; set; }

    public virtual User user { get; set; }
}