// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyFitQuest.API.Models;

public partial class User
{
    public int user_id { get; set; }

    public string username { get; set; }

    public string password_hash { get; set; }

    public string email { get; set; }

    public string phone_number { get; set; }

    public string citizen_id { get; set; }

    public DateTime? created_at { get; set; }

    public DateTime? updated_at { get; set; }

    public virtual ICollection<Audit_Log> Audit_Logs { get; set; } = new List<Audit_Log>();

    public virtual ICollection<Profile> Profiles { get; set; } = new List<Profile>();

    public virtual ICollection<User_Meal_Plan> User_Meal_Plans { get; set; } = new List<User_Meal_Plan>();

    public virtual ICollection<User_Quest> User_Quests { get; set; } = new List<User_Quest>();

    public virtual ICollection<User_Role> User_Roles { get; set; } = new List<User_Role>();

    public virtual ICollection<User_Workout_Plan> User_Workout_Plans { get; set; } = new List<User_Workout_Plan>();
}