// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyFitQuest.API.Models;

public partial class User_Role
{
    public int user_role_id { get; set; }

    public int user_id { get; set; }

    public int role_id { get; set; }

    public virtual Role role { get; set; }

    public virtual User user { get; set; }
}