// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyFitQuest.API.Models;

public partial class User_Workout_Plan
{
    public int user_workout_id { get; set; }

    public int user_id { get; set; }

    public int plan_id { get; set; }

    public DateOnly start_date { get; set; }

    public string status { get; set; }

    public virtual Workout_Plan plan { get; set; }

    public virtual User user { get; set; }
}