// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyFitQuest.API.Models;

public partial class Workout_Plan
{
    public int plan_id { get; set; }

    public string plan_name { get; set; }

    public string description { get; set; }

    public string difficulty { get; set; }

    public int duration_weeks { get; set; }

    public DateTime? created_at { get; set; }

    public DateTime? updated_at { get; set; }

    public virtual ICollection<User_Workout_Plan> User_Workout_Plans { get; set; } = new List<User_Workout_Plan>();
}